# Generated by Django 4.2.3 on 2023-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10, verbose_name='Цена закупки'),
        ),
    ]
