# Generated by Django 4.2.1 on 2023-06-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_shippingaddress_customer_and_more'),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
