# Generated by Django 4.2.1 on 2023-06-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='PaymentAddress',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
