# Generated by Django 4.2.1 on 2023-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='epitaph',
            field=models.TextField(blank=True, null=True, verbose_name='Эпитафия'),
        ),
    ]
