# Generated by Django 4.2.1 on 2023-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_epitaph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermaterial',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='orderstuff',
            options={'verbose_name': 'Файл картинки', 'verbose_name_plural': 'Файлы картинок'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Способ оплаты'},
        ),
        migrations.AddField(
            model_name='service',
            name='price_for_work',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10, verbose_name='Учетная цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='initial_cost',
            field=models.DecimalField(decimal_places=2, default='10.0', max_digits=10, verbose_name='Базовая цена'),
        ),
    ]
