# Generated by Django 4.2.3 on 2023-07-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('density', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='infobase/materials/images')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Виды материалов',
            },
        ),
    ]
