# Generated by Django 4.2.3 on 2023-07-07 04:54

import apps.employees.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('event_type', models.CharField(choices=[('наряд', 'Наряд'), ('встреча', 'Встреча'), ('заказ', 'Заказ'), ('день рождения', 'День рождения'), ('учет', 'Учет'), ('прочее', 'Прочее')], default='прочее', max_length=30, verbose_name='Тип события')),
                ('event_title', models.CharField(max_length=100, verbose_name='Название')),
                ('event_description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Cобытия',
            },
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('hired_date', models.DateField(verbose_name='Дата найма')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('photo', models.ImageField(default='users/default.jpeg', upload_to=apps.employees.models.upload_empl_pic_to)),
                ('photo_thumb', models.ImageField(blank=True, upload_to=apps.employees.models.upload_empl_pic_to)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Добавить аккаунт?')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='От')),
                ('date_to', models.DateField(verbose_name='До')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Премия')),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Аванс')),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого к выплате:')),
                ('issued', models.BooleanField(default=False, verbose_name='Выдано')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Зарплаты',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('UNAPPROVED', 'Неутвержден'), ('APPROVED', 'Утвержден')], default='UNAPPROVED', max_length=20)),
                ('code', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Заказ наряд',
                'verbose_name_plural': 'Заказ наряды',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], default='day', max_length=10, verbose_name='Режим')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('planned_schedule', models.TextField(blank=True, null=True, verbose_name='Планируемый график')),
                ('vacation', models.BooleanField(default=False, verbose_name='Отпуск')),
                ('calendar_event', models.CharField(blank=True, max_length=100, verbose_name='Событие')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Рабочие графики',
            },
        ),
    ]
