# Generated by Django 4.2.3 on 2023-07-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderstuffissued',
            options={'verbose_name_plural': 'Исполнители'},
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='order_confirmed_data',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='order_data',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('рабочий', 'Рабочий'), ('бригадир', 'Бригадир'), ('руководитель', 'Руководитель'), ('специалист', 'Специалист'), ('уборщик', 'Уборщик'), ('продавец', 'Продавец'), ('охранник', 'Охранник')], default='Рабочий', max_length=50, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_responsible', to='employees.employee', verbose_name='Ответственный исполнитель'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('не утвержден', 'Не утвержден'), ('утвержен', 'Утвержден')], default='Черновик', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='percentage_value_add_to_price',
            field=models.IntegerField(verbose_name='Процент от суммы'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.service', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='workorderstuffissued',
            name='order_accept_person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_accept_person', to='employees.employee', verbose_name='Наряд принял:'),
        ),
        migrations.AlterField(
            model_name='workorderstuffissued',
            name='order_confirmed_preson_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmed_person', to='employees.employee', verbose_name='Наряд утвержден'),
        ),
        migrations.AlterField(
            model_name='workorderstuffissued',
            name='order_of_issued_person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_issued_person', to='employees.employee', verbose_name='Наряд выдан:'),
        ),
        migrations.AlterField(
            model_name='workorderstuffissued',
            name='order_of_master_person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_master', to='employees.employee', verbose_name='Бригадир:'),
        ),
    ]
