# Generated by Django 4.2.1 on 2023-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_salary_options_salary_advance_salary_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
