# Generated by Django 4.2.3 on 2023-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
