# Generated by Django 4.2.1 on 2023-07-03 15:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_salary_issued'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': 'Заказ наряд', 'verbose_name_plural': 'Заказ наряды'},
        ),
        migrations.AddField(
            model_name='workorder',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Аванс'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date_from',
            field=models.DateField(verbose_name='От'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date_to',
            field=models.DateField(verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='issued',
            field=models.BooleanField(default=False, verbose_name='Выдано'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого к выплате:'),
        ),
    ]
