# Generated by Django 4.2.1 on 2023-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_workorder_options_workorder_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
