# Generated by Django 4.2.3 on 2023-07-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_services_name_workorder_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='order_code',
            new_name='code',
        ),
    ]
