# Generated by Django 4.2.1 on 2023-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_workshift_options_remove_workshift_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('holiday', 'Holiday'), ('birthday', 'Birthday'), ('other', 'Other')], max_length=10, verbose_name='Тип события')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
