# Generated by Django 4.2.3 on 2023-07-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_order_code_workorder_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Ответственный исполнитель'),
        ),
    ]
