# Generated by Django 4.2.1 on 2023-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_calendarevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name_plural': 'Календарь'},
        ),
        migrations.AlterModelOptions(
            name='workshift',
            options={'verbose_name_plural': 'Рабочие графики'},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='className',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
