# Generated by Django 4.2.3 on 2023-07-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_workorder_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('UNAPPROVED', 'Неутвержден'), ('APPROVED', 'Утвержден'), ('черновик', 'Черновик')], default='Черновик', max_length=20, verbose_name='Статус'),
        ),
    ]
