# Generated by Django 4.2.1 on 2023-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_calendarevent_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='allDay',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='className',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='end',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('встреча', 'Встреча'), ('заказ', 'Заказ'), ('день рождения', 'День рождения'), ('учет', 'Учет'), ('прочее', 'Прочее')], default='прочее', max_length=30, verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
